apiVersion: v1
kind: Secret
metadata:
  name: fastapi-service-secret
stringData:
  JWT_SECRET: ""
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-service
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
spec:
  selector:
    matchLabels:
      app: fastapi-service
  replicas: 8
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
        - name: fastapi-service
          image: fastapi-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: fastapi-service-secret